### ISSUE TITLE
`QueryableBlock::transaction_with_proof` is lending a `Transaction` reference

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/hotshot-query-service#266]
Return type includes `&Self::Transaction`:

https://github.com/EspressoSystems/hotshot-query-service/blob/159eb6c5a0c4775089ff1954d4641d72b18df5ec/src/availability/query_data.rs#L102-L105

This is a problem because I have only the raw tx bytes, not a proper `Transaction` struct. I could construct on one the fly but then I would be returning a reference to a temporary value. Basically, this API forces the implementation to store all transactions as `Transaction`.

Not sure what the right solution is here. I see why you want to return a reference---we should not be cloning a (possibly large) transaction. Do we need to modify `Transaction` itself? Maybe instead of owned `Vec<u8>` it could have a `&[u8]` with lifetime.

**Comment by jbearer** [comment]
I'm afraid giving `Transaction` a lifetime is going to be problematic elsewhere. Maybe this is a good use case for [`Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html) (which I completely forgot existed last time we had a similar conversation), which allows the callee to return a reference if they have one, or an owned value if not. In this particular case there would be no cloning, since we get an owned value from deserialization and return it by move

**Comment by ggutoski** [comment]
Interesting. What I'm hearing is (i) `Transaction` stays as-is, and (ii) the return type of `transaction_with_proof` must be changed to include a `Cow`. Correct?

I don't understand this:

> In this particular case there would be no cloning, since we get an owned value from deserialization and return it by move

If I'm to return a `Transaction` then I need to copy the transaction bytes into a `Vec` before returning.

Or perhaps you intend that `Transaction` itself should be modified to have a `Cow` instead of `Vec`? That would suffice to eliminate all copying. (In that case the return type of `transaction_with_proof` need not change.)

**Comment by jbearer** [comment]
Oh, right, for some reason I thought we would be deserializing a transaction from the raw bytes but actually we're just copying a slice. So, having `Transaction<'a> { bytes: Cow<'a, [u8]> }` would actually be a decent solution here, except I'm just afraid we're gonna run into a lot of annoyances with that lifetime, where we end up working with a `Transaction<'static>` most of the time which requires copying the bytes anyways.

Let's just leave this open for now and do the copy for the short term. I'm not super worried about this copy, as it is analogous to just calling `bincode::deserialize` or something in terms of the amount of data that gets moved around. It just sticks out more because our transaction type is so simple we can see how we *could* get rid of the copy. But if it ever starts to become a performance problem, we can revisit this.

**Comment by jbearer** [comment]
Oh right. Yes.
