### ISSUE TITLE
Index transactions by global position

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/hotshot-query-service#341]
I.e. get the `n`th transaction among all blocks, or get the most recent 50 transactions, etc.

**Comment by jbearer** [comment]
Queries for the `n`th transaction specifically are problematic, because we can't answer this if we don't have all blocks: if we are missing a block we don't necessarily know how many transactions are in it, which throws of the index for every block after it. This makes it hard to even design an index like this in the database, let alone a complete one.

OTOH this index may not be necessary: queries for individual transactions should usually be by hash, or at worst by (block, relative offset) which is much easier to build. And for iterating/paginating transactions, we can just do a flatmap over blocks, and display some kind of warning if blocks are missing (we could even put a placeholder in the stream for "transactions are missing here but we don't know how many").

@Ayiga what do you think -- can we close this issue?

**Comment by Ayiga** [comment]
I think this could work conceptually, but I do foresee some potential problems, that I'm not certain how we'd reconcile.  The first is let's say we want to start at the last `transaction` in the `latest` `block`.  How would we even go about doing this from an `API` `endpoint`?

The only way I can see that we'd have any ability to achieve something like this is with the `block summary`.  But that would require `2` initial requests before we can ultimately make the request we want:

`GET /status/block-height` -> `GET /availability/block/summary/<latest_block_height>` -> `GET /availability/transaction/summaries/<latest_block_height>/<last_transaction_offset>/<count of desired records>`. Assuming, of course, that the `transaction summaries pagination could work like this`.

This **is** feasible but may end up being slower initially as a result.  The next problem I see is potentially not knowing what the previous `query` might be.  Let's say that we just finished displaying a page that ends showing `Block N` at `Offset 0`.  The next Page **should** start at `Block N - 1` with an unknown `offset`.  Again the only way to really get the next offset would be to fetch the `block summary` for `Block N - 1` first.  However, if `Block N - 1` does not exist as you're suggesting, then we may end up having to iterate down to `Block N - 2` and so forth until we find a `block` that **is** populated.

The only other alternative I can think of is to add some sort of `handler` that means "Start at the Last Offset".  Something like

`GET /transaction/summaries/<block_height>/end/<count of desired records>`.  This **should** still be `pure` because the `end` is determined by the `number of `transactions` within the specified `block` itself.

I'm not certain how this would really work with the `Fetch` approach and proactive fetching.  We could submit `block`s to fetch as we iterate over them for non `SQL` `storage` engines, and we'd likely need to build our result set using a `slice::windows` as an `iterator`.  But again, I'm not sure how this would work with the `Fetcher` `trait` for `active_fetch` and `passive_fetch`, as we don't really know where we're going to end until we end.

Regarding using the `hash` to offset from a `transaction`:

If we wanted to use the `hash` of the `transaction` to index the `start`, we might run into an issue, as currently many `transaction`s are generating with the same `hash` at the moment:

| Hash                                                | Block Height | Index |
| --------------------------------------------------- | ------------ | ----- |
| COMMIT~TMxnBi-2b7ekKIcuTOY61IPSoZuvwIQFy7zjLb-iYzjc |       239312 |     0 |
| COMMIT~TMxnBi-2b7ekKIcuTOY61IPSoZuvwIQFy7zjLb-iYzjc |       239311 |     0 |
| COMMIT~TMxnBi-2b7ekKIcuTOY61IPSoZuvwIQFy7zjLb-iYzjc |       239310 |     0 |
| COMMIT~TMxnBi-2b7ekKIcuTOY61IPSoZuvwIQFy7zjLb-iYzjc |       239309 |     0 |
| COMMIT~gQWcRm5Ultc6L9h0aOGhWf_lDSGmTQN7JdqW8iT9efYU |       239304 |     0 |
| COMMIT~gQWcRm5Ultc6L9h0aOGhWf_lDSGmTQN7JdqW8iT9efYU |       239303 |     0 |
| COMMIT~gQWcRm5Ultc6L9h0aOGhWf_lDSGmTQN7JdqW8iT9efYU |       239302 |     0 |
| COMMIT~gQWcRm5Ultc6L9h0aOGhWf_lDSGmTQN7JdqW8iT9efYU |       239301 |     0 |
| COMMIT~SjE1RM16t-iYEA3sc8uZZ3wSplszhIL075kfWfF9ypkb |       239279 |     0 |
| COMMIT~SjE1RM16t-iYEA3sc8uZZ3wSplszhIL075kfWfF9ypkb |       239278 |     0 |
| COMMIT~SjE1RM16t-iYEA3sc8uZZ3wSplszhIL075kfWfF9ypkb |       239277 |     0 |
| COMMIT~SjE1RM16t-iYEA3sc8uZZ3wSplszhIL075kfWfF9ypkb |       239276 |     0 |
| COMMIT~0T5iUXKihEywpQe9xRWLC4xwdOiwHlL08JsYU4ftdwLZ |       239271 |     0 |
| COMMIT~0T5iUXKihEywpQe9xRWLC4xwdOiwHlL08JsYU4ftdwLZ |       239270 |     0 |
| COMMIT~0T5iUXKihEywpQe9xRWLC4xwdOiwHlL08JsYU4ftdwLZ |       239269 |     0 |
| COMMIT~0T5iUXKihEywpQe9xRWLC4xwdOiwHlL08JsYU4ftdwLZ |       239268 |     0 |
| COMMIT~5saqWYUTQLbwW5dTV7SqHfUFkIOV4Q5EKys0pIlUe3Rb |       239247 |     1 |
| COMMIT~UvAdd0O3fSTBzxtt5F_ShcYTK05dJDVtkUdlIcKqwJHK |       239247 |     0 |
| COMMIT~5saqWYUTQLbwW5dTV7SqHfUFkIOV4Q5EKys0pIlUe3Rb |       239246 |     1 |
| COMMIT~UvAdd0O3fSTBzxtt5F_ShcYTK05dJDVtkUdlIcKqwJHK |       239246 |     0 |

So currently the `transaction hash` does **NOT** indicate a unique position for `transactions`.  In addition there's not real way for anyone to know with the `N - 1` `transaction` `hash` is going to be, as they're not going to be predictable.  In that way, it seems like the `hash` could only really be used to look up a `transaction`, but even then since they're not currently unique, that even seems to be not guaranteed / problematic.

**Comment by jbearer** [comment]
Oh yeah, I forgot hashes are not unique. We would only use them for looking up individual transactions anyways, not iterating, and then we could alternatively use `(block height, tx offset)` as a unique ID.

As for iterating, I would suggest doing basically what you're suggesting, but doing it in the backend. The frontend can use the globally unique ID as a cursor to start from, and then request a certain number of transactions forwards or backwards. Don't worry about block boundaries or finding the next non-empty/non-missing block, or finding the length of a block. The backend will do all that. So if your cursor is currently at `(block: x, tx: y)`, and the user clicks the previous page button, you could do some query like `/availability/transactions/from/x/y/reverse/limit/50` or something. A bit messy but maybe not the end of the world.

Then in the backend we can get a stream of transactions across block boundaries with implicit fetching and bulk loading like this:
```rust
state
    .get_block_range(..x)
    .rev()
    .flat_map(|fetch| match fetch.try_resolve() {
        Ok(block) => block.enumerate().map(Some).collect(),
        Err(_) => vec![None],
    })
    .skip(y)
    .take(50)
```
This is just a sketch but basically you want to get a descending stream of blocks starting at x, for every block which is currently available  we flatten it into a stream of transactions (wrapped in `Some`), for every block which is not available, we insert a placeholder `None` into the stream (this will turn into `null` in the JSON).

Now the only issue is that this is not technically "pure". A simple solution for that is to put it under `node` instead of `availability`; the whole point of the `node` API is to return stuff that might be reflected differently on different nodes based on the sync status. However, that's a bit messy as this query is basically just using `AvailabilityDataSource`.

Another option would be to adopt a new convention where we mark certain availability endpoints as `partial`, e.g. `availability/partial/transactions/from/:height/:offset/limit/:limit`. We can then document that these endpoints are pure modulo missing data that might be substituted with a placeholder. This is not so different from our current endpoints which our pure modulo missing data that might cause them to fail. For consistency we would then want to do a similar thing for the other paginated endpoints as well.

**Comment by jbearer** [comment]
Alternatively, instead of doing all this placeholder stuff for missing data, you could do `availability/stream/transactions` which uses the same kind of pagination but opens up a WebSockets connection. This then allows you to block until missing data becomes available. In practice missing data should be resolved rather quickly, especially if the client is actively requesting it, so maybe this is ok. Then we never have to surface missing data to the user at all.
